version: '3'

services:
  db:
    image: mongo
    env_file:
      - .env
    volumes:
      - mongodb_data:/data/db
    ports:
    - "27017:27017"
  web_app:
    build:
      dockerfile: Dockerfile
      context: .
    image:  bmat
    volumes:
      - ./app:/opt/app
      - ./tests:/opt/tests
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "5000:80"

volumes:
  mongodb_data:
    external: true