version: '3'

services:
  db:
    image: mongo
    env_file:
      - .env
    volumes:
      - mongodb_data:/data/db
  web_app:
    build:
      dockerfile: Dockerfile
      context: .
    image:  bmat
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "5000:5000"

volumes:
  mongodb_data:
    external: true